<!DOCTYPE HTML>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?php
        if (isset($model->page_title)) {
            ?>
            <title><?php echo $model->page_title; ?></title>
            <?php
        }
        foreach ($this->config['resources']['css'] as $name => $url) {
            echo '<link rel="stylesheet" href="' . $url . '" integrity="' . $this->config['resources']['css-sri'][$name] . '" crossorigin="anonymous" />' . PHP_EOL;
        }
        foreach ($styles as $style) {
            if (empty($style['url']) || empty($style['sri'])) {
                continue;
            }
            echo '<link rel="stylesheet" href="' . $style['url'] . '" integrity="' . $style['sri'] . '" crossorigin="anonymous" />' . PHP_EOL;
        }
        ?>
    </head>
    <body>
        <?php
        require dirname(__FILE__) . '/' . $page;
        echo PHP_EOL;
        foreach ($this->config['resources']['js'] as $name => $url) {
            echo '<script type="text/javascript" src="' . $url . '" integrity="' . $this->config['resources']['js-sri'][$name] . '" crossorigin="anonymous"></script>' . PHP_EOL;
        }
        foreach ($scripts as $script) {
            if (empty($script['url']) || empty($script['sri'])) {
                continue;
            }
            echo '<script type="text/javascript" src="' . $script['url'] . '" integrity="' . $script['sri'] . '" crossorigin="anonymous"></script>' . PHP_EOL;
        }
        if (isset($model)) {
            if ($this->config['steel']['useLang']) {
                ?>
                <script src="/js/steel_localizer.js" type="text/javascript"></script>
                <?php
            }
        }
        ?>
    </body>
</html>
