<!DOCTYPE HTML>
<html>
    <head>
    <?php
    	foreach ($this->model->steel->config['resources']['css'] as $name => $url){
    		echo '<link rel="stylesheet" href="'.$url.'" integrity="'.$this->model->steel->config['resources']['css-sri'][$name].'" crossorigin="anonymous" />';
    	}
    ?>
    </head>
    <body>
        <?php
        require dirname(__FILE__) . '/' . $page;
        ?>
    </body>
    <?php 
	    foreach ($this->model->steel->config['resources']['js'] as $name => $url){
	    	echo '<script type="text/javascript" src="'.$url.'" integrity="'.$this->model->steel->config['resources']['js-sri'][$name].'" crossorigin="anonymous"></script>';
	    }
	    if(isset($this->model) && isset($this->model->steel)){
	    	if($this->model->steel->config['steel']['useLang']){
	    		?>
	    		<script src="/js/steel_localizer.js" type="text/javascript"></script>
	    		<?php
	    	}
	    }
    ?>
</html>