<div class="container">
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand">Steel <?php echo $model->navbar_title; ?></a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="#">Home</a></li>
                    <li><a href="http://ericrabil.github.io/steel-framework/api/latest/">API</a></li>
                    <li><a href="https://www.github.com/EricRabil/steel-framework">GitHub</a></li>
                    <li><a href="https://www.github.com/EricRabil/steel-framework/wiki">Wiki</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="active">
                        <?php
                        switch ($this->config['steel']['type']) {
                            case "canary":
                                ?>
                                <a style="color:#d35552">Beta
                                    <?php
                                    break;
                                case "release-candidate":
                                    ?>
                                    <a style="color:#dba03b" >Pre-Release
                                        <?php
                                        break;
                                    case "release":
                                        ?>
                                        <a style="color:#57af59">Release
                                            <?php
                                            break;
                                    }
                                    ?>
                                </a></li>
                                </ul>
                                </div><!--/.nav-collapse -->
                                </div><!--/.container-fluid -->
                                </nav>

                                <div class="jumbotron">
                                    <h1>Welcome to Steel</h1>
                                    <p class="lead">Steel is an easy-to-use framework built from the ground up to give you the tools you need to build your application.</p>
                                    <p><a class="btn btn-lg btn-info" href="https://www.github.com/EricRabil/steel-framework/wiki" role="button">Read the docs</a></p>
                                </div>

                                <div class="row marketing">
                                    <div class="col-lg-12">
                                        <h4>Why am I seeing this page?</h4>
                                        <p>This is the default MVC for the Steel Framework. It is used in place of an ugly "Hello World!" screen :)</p>
                                    </div>

                                    <div class="col-lg-12">
                                        <h4>Quick-Start</h4>
                                        <ul class="list-group">
                                            <li class="list-group-item active">To start making your app (hopefully you've read the docs and know how to make an app,) you need to configure Steel. Open up <b>/classes/Steel/Settings.php</b> and configure the following to get started:</li>
                                            <li class="list-group-item">If you have files to include into Steel, set ['steel']['autoinclude'] to true and place your PHP files in the <b>/include</b> directory.</li>
                                            <li class="list-group-item">If you'll be using an Application to hook into Steel, set ['steel']['useApplication'] to true and make sure your ['steel']['application'] is properly entered. Check the wiki for more info.</li>
                                            <li class="list-group-item">If you plan on using sessions, set ['steel']['useSessions'] to true.</li>
                                            <li class="list-group-item">If you plan on using the integrated localizer, set ['steel']['useLang'] to true.</li>
                                            <li class="list-group-item">The ['resources']['css'] and ['resources']['js'] arrays are arrays that autoload your resources. This requires Subresource Integrity (hashing of files to prevent unwanted file modification - hashes can be generated <a href="https://srihash.org">here</a>.) If you want to add your own resources, just follow the format of the entries already there.</li>
                                            <li class="list-group-item">Change ['general']['host'] to the domain name you want pages to redirect to. EX: <b>{['general']['host']}/error/404</b> </li>
                                            <li class="list-group-item">Configure ['database'] to meet your database criteria if you plan on using the built in database system.</li>
                                            <li class="list-group-item">Lastly, when you're ready, set ['steel']['postinst'] to false. That will disable this page and let you get to work!</li>
                                        </ul>
                                    </div>
                                </div>

                                <footer class="footer">
                                    <p>Made with love and the MIT license</p>
                                </footer>

                                </div>